services:
  gin-app:
    hostname: apptest
    build:
      context: ../
      dockerfile: ./cmd/gin_app/Dockerfile 
    ports:
      - "8080:8080" 
    volumes:
      - ../metrics_data/logs:/app/metrics_data/logs:rw  
      - ../metrics_data/pandora_results:/app/metrics_data/pandora_results:rw  
      - ../metrics_data/prometheus:/app/metrics_data/prometheus:rw  
    environment:
      - GIN_MODE=release
    deploy:
      resources:
        limits:
          cpus: "1.0"        
          memory: 1g         
    networks:
      - benchmark-gin-fiber-network

  fiber-app:
    hostname: apptest
    build:
      context: ../
      dockerfile: ./cmd/fiber_app/Dockerfile 
    ports:
      - "8080:8080"
    volumes:
      - ../metrics_data/logs:/app/metrics_data/logs:rw  
      - ../metrics_data/pandora_results:/app/metrics_data/pandora_results:rw  
      - ../metrics_data/prometheus:/app/metrics_data/prometheus:rw  
    deploy:
      resources:
        limits:
          cpus: "1.0"        
          memory: 1g  
    networks:
      - benchmark-gin-fiber-network

  prometheus:
    container_name: test-prometheus
    hostname: testprom
    image: prom/prometheus:latest
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - benchmark-gin-fiber-network

  cadvisortest:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisortest
    hostname: cadvisortest
    ports:
      - "8081:8081" # 8081:8080 - 8081 - порт на хосте (вашей машине) 8080 - порт внутри контейнера
      # компьютер -> 8081 -> 8080 -> приложение на порту 8080
    command: ["-port", "8081"]
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /mnt/windows_docker/:/var/lib/docker:ro # особенность wsl
      - /mnt/windows_docker/:/rootfs/var/lib/docker:ro  # особенность wsl
    networks:
      - benchmark-gin-fiber-network

networks:
  benchmark-gin-fiber-network:
    driver: bridge
    name: benchmark-gin-fiber-network

volumes:
  prometheus_data: