pools:
  - id: Flat Endpoint Load
    gun:
      type: http
      target: "localhost:8081"  # Ваш базовый URL
    ammo:
      type: http/json 
      file: "./requests/ammo/flat_ammo.json"
    result:
      type: phout
      destination: "./pandora_results/flat_results.phout"
    rps:
      - duration: 10s
        type: const
        ops: 1  # 1 запрос в секунду
    startup:
      type: once
      times: 1  # Выполнить весь ammo один раз 
